################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/STM32N6_WS/STM32N6-NPU-Setup/Middlewares/ST/STM32_ExtMem_Manager/boot/stm32_boot_lrun.c \
D:/STM32N6_WS/STM32N6-NPU-Setup/Middlewares/ST/STM32_ExtMem_Manager/stm32_extmem.c \
D:/STM32N6_WS/STM32N6-NPU-Setup/Middlewares/ST/STM32_ExtMem_Manager/psram/stm32_psram_driver.c \
D:/STM32N6_WS/STM32N6-NPU-Setup/Middlewares/ST/STM32_ExtMem_Manager/sal/stm32_sal_sd.c \
D:/STM32N6_WS/STM32N6-NPU-Setup/Middlewares/ST/STM32_ExtMem_Manager/sal/stm32_sal_xspi.c \
D:/STM32N6_WS/STM32N6-NPU-Setup/Middlewares/ST/STM32_ExtMem_Manager/sdcard/stm32_sdcard_driver.c \
D:/STM32N6_WS/STM32N6-NPU-Setup/Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp/stm32_sfdp_data.c \
D:/STM32N6_WS/STM32N6-NPU-Setup/Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp/stm32_sfdp_driver.c \
D:/STM32N6_WS/STM32N6-NPU-Setup/Middlewares/ST/STM32_ExtMem_Manager/user/stm32_user_driver.c 

OBJS += \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_boot_lrun.o \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_extmem.o \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_psram_driver.o \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_sal_sd.o \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_sal_xspi.o \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_sdcard_driver.o \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_sfdp_data.o \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_sfdp_driver.o \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_user_driver.o 

C_DEPS += \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_boot_lrun.d \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_extmem.d \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_psram_driver.d \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_sal_sd.d \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_sal_xspi.d \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_sdcard_driver.d \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_sfdp_data.d \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_sfdp_driver.d \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_user_driver.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/ST/STM32_ExtMem_Manager/stm32_boot_lrun.o: D:/STM32N6_WS/STM32N6-NPU-Setup/Middlewares/ST/STM32_ExtMem_Manager/boot/stm32_boot_lrun.c Middlewares/ST/STM32_ExtMem_Manager/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -DUSE_NUCLEO_64 -c -I../Core/Inc -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/BSP/STM32N6xx_Nucleo -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/STM32_ExtMem_Manager -I../../Middlewares/ST/STM32_ExtMem_Manager/boot -I../../Middlewares/ST/STM32_ExtMem_Manager/sal -I../../Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp -I../../Middlewares/ST/STM32_ExtMem_Manager/psram -I../../Middlewares/ST/STM32_ExtMem_Manager/sdcard -I../../Middlewares/ST/STM32_ExtMem_Manager/user -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ST/STM32_ExtMem_Manager/stm32_extmem.o: D:/STM32N6_WS/STM32N6-NPU-Setup/Middlewares/ST/STM32_ExtMem_Manager/stm32_extmem.c Middlewares/ST/STM32_ExtMem_Manager/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -DUSE_NUCLEO_64 -c -I../Core/Inc -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/BSP/STM32N6xx_Nucleo -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/STM32_ExtMem_Manager -I../../Middlewares/ST/STM32_ExtMem_Manager/boot -I../../Middlewares/ST/STM32_ExtMem_Manager/sal -I../../Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp -I../../Middlewares/ST/STM32_ExtMem_Manager/psram -I../../Middlewares/ST/STM32_ExtMem_Manager/sdcard -I../../Middlewares/ST/STM32_ExtMem_Manager/user -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ST/STM32_ExtMem_Manager/stm32_psram_driver.o: D:/STM32N6_WS/STM32N6-NPU-Setup/Middlewares/ST/STM32_ExtMem_Manager/psram/stm32_psram_driver.c Middlewares/ST/STM32_ExtMem_Manager/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -DUSE_NUCLEO_64 -c -I../Core/Inc -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/BSP/STM32N6xx_Nucleo -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/STM32_ExtMem_Manager -I../../Middlewares/ST/STM32_ExtMem_Manager/boot -I../../Middlewares/ST/STM32_ExtMem_Manager/sal -I../../Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp -I../../Middlewares/ST/STM32_ExtMem_Manager/psram -I../../Middlewares/ST/STM32_ExtMem_Manager/sdcard -I../../Middlewares/ST/STM32_ExtMem_Manager/user -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ST/STM32_ExtMem_Manager/stm32_sal_sd.o: D:/STM32N6_WS/STM32N6-NPU-Setup/Middlewares/ST/STM32_ExtMem_Manager/sal/stm32_sal_sd.c Middlewares/ST/STM32_ExtMem_Manager/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -DUSE_NUCLEO_64 -c -I../Core/Inc -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/BSP/STM32N6xx_Nucleo -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/STM32_ExtMem_Manager -I../../Middlewares/ST/STM32_ExtMem_Manager/boot -I../../Middlewares/ST/STM32_ExtMem_Manager/sal -I../../Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp -I../../Middlewares/ST/STM32_ExtMem_Manager/psram -I../../Middlewares/ST/STM32_ExtMem_Manager/sdcard -I../../Middlewares/ST/STM32_ExtMem_Manager/user -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ST/STM32_ExtMem_Manager/stm32_sal_xspi.o: D:/STM32N6_WS/STM32N6-NPU-Setup/Middlewares/ST/STM32_ExtMem_Manager/sal/stm32_sal_xspi.c Middlewares/ST/STM32_ExtMem_Manager/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -DUSE_NUCLEO_64 -c -I../Core/Inc -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/BSP/STM32N6xx_Nucleo -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/STM32_ExtMem_Manager -I../../Middlewares/ST/STM32_ExtMem_Manager/boot -I../../Middlewares/ST/STM32_ExtMem_Manager/sal -I../../Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp -I../../Middlewares/ST/STM32_ExtMem_Manager/psram -I../../Middlewares/ST/STM32_ExtMem_Manager/sdcard -I../../Middlewares/ST/STM32_ExtMem_Manager/user -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ST/STM32_ExtMem_Manager/stm32_sdcard_driver.o: D:/STM32N6_WS/STM32N6-NPU-Setup/Middlewares/ST/STM32_ExtMem_Manager/sdcard/stm32_sdcard_driver.c Middlewares/ST/STM32_ExtMem_Manager/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -DUSE_NUCLEO_64 -c -I../Core/Inc -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/BSP/STM32N6xx_Nucleo -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/STM32_ExtMem_Manager -I../../Middlewares/ST/STM32_ExtMem_Manager/boot -I../../Middlewares/ST/STM32_ExtMem_Manager/sal -I../../Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp -I../../Middlewares/ST/STM32_ExtMem_Manager/psram -I../../Middlewares/ST/STM32_ExtMem_Manager/sdcard -I../../Middlewares/ST/STM32_ExtMem_Manager/user -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ST/STM32_ExtMem_Manager/stm32_sfdp_data.o: D:/STM32N6_WS/STM32N6-NPU-Setup/Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp/stm32_sfdp_data.c Middlewares/ST/STM32_ExtMem_Manager/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -DUSE_NUCLEO_64 -c -I../Core/Inc -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/BSP/STM32N6xx_Nucleo -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/STM32_ExtMem_Manager -I../../Middlewares/ST/STM32_ExtMem_Manager/boot -I../../Middlewares/ST/STM32_ExtMem_Manager/sal -I../../Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp -I../../Middlewares/ST/STM32_ExtMem_Manager/psram -I../../Middlewares/ST/STM32_ExtMem_Manager/sdcard -I../../Middlewares/ST/STM32_ExtMem_Manager/user -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ST/STM32_ExtMem_Manager/stm32_sfdp_driver.o: D:/STM32N6_WS/STM32N6-NPU-Setup/Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp/stm32_sfdp_driver.c Middlewares/ST/STM32_ExtMem_Manager/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -DUSE_NUCLEO_64 -c -I../Core/Inc -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/BSP/STM32N6xx_Nucleo -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/STM32_ExtMem_Manager -I../../Middlewares/ST/STM32_ExtMem_Manager/boot -I../../Middlewares/ST/STM32_ExtMem_Manager/sal -I../../Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp -I../../Middlewares/ST/STM32_ExtMem_Manager/psram -I../../Middlewares/ST/STM32_ExtMem_Manager/sdcard -I../../Middlewares/ST/STM32_ExtMem_Manager/user -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ST/STM32_ExtMem_Manager/stm32_user_driver.o: D:/STM32N6_WS/STM32N6-NPU-Setup/Middlewares/ST/STM32_ExtMem_Manager/user/stm32_user_driver.c Middlewares/ST/STM32_ExtMem_Manager/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -DUSE_NUCLEO_64 -c -I../Core/Inc -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/BSP/STM32N6xx_Nucleo -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/STM32_ExtMem_Manager -I../../Middlewares/ST/STM32_ExtMem_Manager/boot -I../../Middlewares/ST/STM32_ExtMem_Manager/sal -I../../Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp -I../../Middlewares/ST/STM32_ExtMem_Manager/psram -I../../Middlewares/ST/STM32_ExtMem_Manager/sdcard -I../../Middlewares/ST/STM32_ExtMem_Manager/user -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-ST-2f-STM32_ExtMem_Manager

clean-Middlewares-2f-ST-2f-STM32_ExtMem_Manager:
	-$(RM) ./Middlewares/ST/STM32_ExtMem_Manager/stm32_boot_lrun.cyclo ./Middlewares/ST/STM32_ExtMem_Manager/stm32_boot_lrun.d ./Middlewares/ST/STM32_ExtMem_Manager/stm32_boot_lrun.o ./Middlewares/ST/STM32_ExtMem_Manager/stm32_boot_lrun.su ./Middlewares/ST/STM32_ExtMem_Manager/stm32_extmem.cyclo ./Middlewares/ST/STM32_ExtMem_Manager/stm32_extmem.d ./Middlewares/ST/STM32_ExtMem_Manager/stm32_extmem.o ./Middlewares/ST/STM32_ExtMem_Manager/stm32_extmem.su ./Middlewares/ST/STM32_ExtMem_Manager/stm32_psram_driver.cyclo ./Middlewares/ST/STM32_ExtMem_Manager/stm32_psram_driver.d ./Middlewares/ST/STM32_ExtMem_Manager/stm32_psram_driver.o ./Middlewares/ST/STM32_ExtMem_Manager/stm32_psram_driver.su ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sal_sd.cyclo ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sal_sd.d ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sal_sd.o ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sal_sd.su ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sal_xspi.cyclo ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sal_xspi.d ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sal_xspi.o ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sal_xspi.su ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sdcard_driver.cyclo ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sdcard_driver.d ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sdcard_driver.o ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sdcard_driver.su ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sfdp_data.cyclo ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sfdp_data.d ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sfdp_data.o ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sfdp_data.su ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sfdp_driver.cyclo ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sfdp_driver.d ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sfdp_driver.o ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sfdp_driver.su ./Middlewares/ST/STM32_ExtMem_Manager/stm32_user_driver.cyclo ./Middlewares/ST/STM32_ExtMem_Manager/stm32_user_driver.d ./Middlewares/ST/STM32_ExtMem_Manager/stm32_user_driver.o ./Middlewares/ST/STM32_ExtMem_Manager/stm32_user_driver.su

.PHONY: clean-Middlewares-2f-ST-2f-STM32_ExtMem_Manager

